### PR TITLE
Develop -> Master

### PR DESCRIPTION
**Pull request by lukasyelle**
Adds new features and fixes bugs.

### CODE REVIEW

**Comment by lukasyelle** [comment]
@zujko So this will be a detriment to code coverage, but the changes aren't really things we can test well so I'm just going to merge it if you think that'll be alright. Thoughts?

**Comment by omardlhz** [comment]
> @zujko So this will be a detriment to code coverage, but the changes aren't really things we can test well so I'm just going to merge it if you think that'll be alright. Thoughts?

If the modules can't really be tested, you can always modify your `.codecov.yml` to ignore that specific file/module. For example:

```yaml
coverage:
  ignore:
    - "app/email"

```

**Comment by zujko** [comment]
@lukasyelle Just merge it, we can deal with it later.

**Comment by lukasyelle** [comment]
That is fair, will do!

**Pull request merged**
